fix: correct file paths for copying keyboard firmware and keymap in compile workflow

diff --git a/.github/workflows/compile-firmware-workflow-call.yaml b/.github/workflows/compile-firmware-workflow-call.yaml
--- a/.github/workflows/compile-firmware-workflow-call.yaml
+++ b/.github/workflows/compile-firmware-workflow-call.yaml
@@ -82,8 +82,8 @@ jobs:
       - name: Copy my keyboards into qmk_firmsware
         run: |
           mkdir -p ~/vial-qmk/keyboards/${KEYBOARD_NAME}
-          cp -r ${KEYBOARD_NAME}_firmware/* ~/vial-qmk/keyboards/${KEYBOARD_NAME}/ || echo 'failed to copy'
-          cp -r ${KEYBOARD_NAME}_keymap/* ~/vial-qmk/keyboards/${KEYBOARD_NAME}/ || echo 'failed to copy'
+          cp -r ./${KEYBOARD_NAME}_firmware/* ~/vial-qmk/keyboards/${KEYBOARD_NAME}/ || echo 'failed to copy'
+          cp -r ./${KEYBOARD_NAME}_keymap/* ~/vial-qmk/keyboards/${KEYBOARD_NAME}/ || echo 'failed to copy'
         env:
           KEYBOARD_NAME: "${{ inputs.keyboard }}"
       - name: Compile
@@ -97,7 +97,7 @@ jobs:
         run: |
           mkdir -p ~/artifacts
           cp ~/vial-qmk/${KEYBOARD_NAME}_${KEYMAP_NAME}.hex ~/artifacts/
-          cp ./LICENSE ~/artifacts/
+          cp ./${KEYBOARD_NAME}_keymap/LICENSE ~/artifacts/
         env:
           KEYBOARD_NAME: "${{ inputs.keyboard }}"
           KEYMAP_NAME: ${{ inputs.keymap }}
